package com.creditharmony.loan.borrow.payback.entity;

import java.util.Date;

import com.creditharmony.core.persistence.DataEntity;
/**
 * 
 * @author 
 *
 */
@SuppressWarnings("serial")
public class BankPlantPort extends DataEntity<BankPlantPort>{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.id
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.bank_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.plant_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String plantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.bank_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.plant_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String plantName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.batch_flag
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String batchFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.is_concentrate
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String isConcentrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.create_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.create_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.modify_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column jk.t_jk_bank_plant_port.modify_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.id
	 * @return  the value of jk.t_jk_bank_plant_port.id
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.id
	 * @param id  the value for jk.t_jk_bank_plant_port.id
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.bank_code
	 * @return  the value of jk.t_jk_bank_plant_port.bank_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.bank_code
	 * @param bankCode  the value for jk.t_jk_bank_plant_port.bank_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode == null ? null : bankCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.plant_code
	 * @return  the value of jk.t_jk_bank_plant_port.plant_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getPlantCode() {
		return plantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.plant_code
	 * @param plantCode  the value for jk.t_jk_bank_plant_port.plant_code
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode == null ? null : plantCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.bank_name
	 * @return  the value of jk.t_jk_bank_plant_port.bank_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.bank_name
	 * @param bankName  the value for jk.t_jk_bank_plant_port.bank_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName == null ? null : bankName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.plant_name
	 * @return  the value of jk.t_jk_bank_plant_port.plant_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getPlantName() {
		return plantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.plant_name
	 * @param plantName  the value for jk.t_jk_bank_plant_port.plant_name
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setPlantName(String plantName) {
		this.plantName = plantName == null ? null : plantName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.batch_flag
	 * @return  the value of jk.t_jk_bank_plant_port.batch_flag
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getBatchFlag() {
		return batchFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.batch_flag
	 * @param batchFlag  the value for jk.t_jk_bank_plant_port.batch_flag
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setBatchFlag(String batchFlag) {
		this.batchFlag = batchFlag == null ? null : batchFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.is_concentrate
	 * @return  the value of jk.t_jk_bank_plant_port.is_concentrate
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getIsConcentrate() {
		return isConcentrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.is_concentrate
	 * @param isConcentrate  the value for jk.t_jk_bank_plant_port.is_concentrate
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setIsConcentrate(String isConcentrate) {
		this.isConcentrate = isConcentrate == null ? null : isConcentrate
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.create_by
	 * @return  the value of jk.t_jk_bank_plant_port.create_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.create_by
	 * @param createBy  the value for jk.t_jk_bank_plant_port.create_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.create_time
	 * @return  the value of jk.t_jk_bank_plant_port.create_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.create_time
	 * @param createTime  the value for jk.t_jk_bank_plant_port.create_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.modify_by
	 * @return  the value of jk.t_jk_bank_plant_port.modify_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.modify_by
	 * @param modifyBy  the value for jk.t_jk_bank_plant_port.modify_by
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy == null ? null : modifyBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column jk.t_jk_bank_plant_port.modify_time
	 * @return  the value of jk.t_jk_bank_plant_port.modify_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column jk.t_jk_bank_plant_port.modify_time
	 * @param modifyTime  the value for jk.t_jk_bank_plant_port.modify_time
	 * @mbggenerated  Wed Apr 20 10:41:44 CST 2016
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}