package com.creditharmony.loan.webservice.infodisclosure.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T10:01:30.491+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.infodisclosure.webservice.loan.creditharmony.com/", name = "InfoDisclosureService")
@XmlSeeAlso({ObjectFactory.class})
public interface InfoDisclosureService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDetailInfo", targetNamespace = "http://service.infodisclosure.webservice.loan.creditharmony.com/", className = "com.creditharmony.loan.webservice.infodisclosure.client.GetDetailInfo")
    @WebMethod
    @ResponseWrapper(localName = "getDetailInfoResponse", targetNamespace = "http://service.infodisclosure.webservice.loan.creditharmony.com/", className = "com.creditharmony.loan.webservice.infodisclosure.client.GetDetailInfoResponse")
    public com.creditharmony.loan.webservice.infodisclosure.client.InfoDisclosure getDetailInfo(
        @WebParam(name = "contractCode", targetNamespace = "")
        java.lang.String contractCode
    );
}
