
package com.creditharmony.loan.webservice.infodisclosure.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T10:01:30.512+08:00
 * Generated source version: 3.1.6
 * 
 */
 
public class InfoDisclosureService_InfoDisclosureServiceImplPort_Server{

    protected InfoDisclosureService_InfoDisclosureServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new InfoDisclosureServiceImplPortImpl();
        String address = "http://localhost:8080/chp-loan/ws/InfoDisclosure";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new InfoDisclosureService_InfoDisclosureServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
