package com.creditharmony.loan.webservice.infodisclosure.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T10:01:30.527+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "InfoDisclosureServiceImplService", 
                  wsdlLocation = "http://localhost:8080/chp-loan/ws/InfoDisclosure?wsdl",
                  targetNamespace = "http://service.infodisclosure.webservice.loan.creditharmony.com/") 
public class InfoDisclosureServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.infodisclosure.webservice.loan.creditharmony.com/", "InfoDisclosureServiceImplService");
    public final static QName InfoDisclosureServiceImplPort = new QName("http://service.infodisclosure.webservice.loan.creditharmony.com/", "InfoDisclosureServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/chp-loan/ws/InfoDisclosure?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfoDisclosureServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/chp-loan/ws/InfoDisclosure?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfoDisclosureServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfoDisclosureServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoDisclosureServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InfoDisclosureServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfoDisclosureServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfoDisclosureServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns InfoDisclosureService
     */
    @WebEndpoint(name = "InfoDisclosureServiceImplPort")
    public InfoDisclosureService getInfoDisclosureServiceImplPort() {
        return super.getPort(InfoDisclosureServiceImplPort, InfoDisclosureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoDisclosureService
     */
    @WebEndpoint(name = "InfoDisclosureServiceImplPort")
    public InfoDisclosureService getInfoDisclosureServiceImplPort(WebServiceFeature... features) {
        return super.getPort(InfoDisclosureServiceImplPort, InfoDisclosureService.class, features);
    }

}
