
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.creditharmony.loan.webservice.infodisclosure.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T10:01:30.469+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "InfoDisclosureServiceImplService",
                      portName = "InfoDisclosureServiceImplPort",
                      targetNamespace = "http://service.infodisclosure.webservice.loan.creditharmony.com/",
                      wsdlLocation = "http://localhost:8080/chp-loan/ws/InfoDisclosure?wsdl",
                      endpointInterface = "com.creditharmony.loan.webservice.infodisclosure.client.InfoDisclosureService")
                      
public class InfoDisclosureServiceImplPortImpl implements InfoDisclosureService {

    private static final Logger LOG = Logger.getLogger(InfoDisclosureServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.creditharmony.loan.webservice.infodisclosure.client.InfoDisclosureService#getDetailInfo(java.lang.String  contractCode )*
     */
    public com.creditharmony.loan.webservice.infodisclosure.client.InfoDisclosure getDetailInfo(java.lang.String contractCode) { 
        LOG.info("Executing operation getDetailInfo");
        System.out.println(contractCode);
        try {
            com.creditharmony.loan.webservice.infodisclosure.client.InfoDisclosure _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
