package com.creditharmony.loan.borrow.pushdata.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PaybackList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.id
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.month_id
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String monthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.contract_code
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.customer_name
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.stores_name
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String storesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.apply_bank_name
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String applyBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.tel
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.month_pay_day
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private Date monthPayDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.months
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private Integer months;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.repay_amount
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private BigDecimal repayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.complete_amount
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private BigDecimal completeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.bule_amount
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private BigDecimal buleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.dict_month_status
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String dictMonthStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.status
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.mark
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.dict_deal_type
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String dictDealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.stores_mark
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String storesMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.stores_mark_userid
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String storesMarkUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.riskcontrol_mark
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String riskcontrolMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.riskcontrol_remark_userid
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String riskcontrolRemarkUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.create_by
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.create_time
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.modify_by
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.modify_time
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private Date modifyTime;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.return_reasion
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private String returnReasion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_jk_payback_list.month_pay_total
     *
     * @mbggenerated Thu Apr 07 11:20:24 CST 2016
     */
    private BigDecimal monthPayTotal;
    
    /**
     * 催收方式
     */
    private String dunningWay;
    
    /**
     * 短信内容
     */
    private String payBackSmsContext;
    /**
     * 短信模板名称
     */
    private String smsModelName;
    /**
     * 借款编号
     */
    private String loanCode;
    /**
     * 客户编号
     */
    private String customerCode;
    /**
     * 还款银行账号
     */
    private String bankAccount;
    

	public String getBankAccount() {
		return bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getDunningWay() {
		return dunningWay;
	}

	public void setDunningWay(String dunningWay) {
		this.dunningWay = dunningWay;
	}

	public String getLoanCode() {
		return loanCode;
	}

	public void setLoanCode(String loanCode) {
		this.loanCode = loanCode;
	}

	public String getCustomerCode() {
		return customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getPayBackSmsContext() {
		return payBackSmsContext;
	}

	public void setPayBackSmsContext(String payBackSmsContext) {
		this.payBackSmsContext = payBackSmsContext;
	}

	public String getSmsModelName() {
		return smsModelName;
	}

	public void setSmsModelName(String smsModelName) {
		this.smsModelName = smsModelName;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.id
     *
     * @param id the value for jk.t_jk_payback_list.id
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.month_id
     *
     * @return the value of jk.t_jk_payback_list.month_id
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getMonthId() {
        return monthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.month_id
     *
     * @param monthId the value for jk.t_jk_payback_list.month_id
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setMonthId(String monthId) {
        this.monthId = monthId == null ? null : monthId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.contract_code
     *
     * @return the value of jk.t_jk_payback_list.contract_code
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.contract_code
     *
     * @param contractCode the value for jk.t_jk_payback_list.contract_code
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.customer_name
     *
     * @return the value of jk.t_jk_payback_list.customer_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.customer_name
     *
     * @param customerName the value for jk.t_jk_payback_list.customer_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.stores_name
     *
     * @return the value of jk.t_jk_payback_list.stores_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getStoresName() {
        return storesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.stores_name
     *
     * @param storesName the value for jk.t_jk_payback_list.stores_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setStoresName(String storesName) {
        this.storesName = storesName == null ? null : storesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.apply_bank_name
     *
     * @return the value of jk.t_jk_payback_list.apply_bank_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getApplyBankName() {
        return applyBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.apply_bank_name
     *
     * @param applyBankName the value for jk.t_jk_payback_list.apply_bank_name
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setApplyBankName(String applyBankName) {
        this.applyBankName = applyBankName == null ? null : applyBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.tel
     *
     * @return the value of jk.t_jk_payback_list.tel
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.tel
     *
     * @param tel the value for jk.t_jk_payback_list.tel
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.month_pay_day
     *
     * @return the value of jk.t_jk_payback_list.month_pay_day
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public Date getMonthPayDay() {
        return monthPayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.month_pay_day
     *
     * @param monthPayDay the value for jk.t_jk_payback_list.month_pay_day
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setMonthPayDay(Date monthPayDay) {
        this.monthPayDay = monthPayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.months
     *
     * @return the value of jk.t_jk_payback_list.months
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.months
     *
     * @param months the value for jk.t_jk_payback_list.months
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.repay_amount
     *
     * @return the value of jk.t_jk_payback_list.repay_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public BigDecimal getRepayAmount() {
        return repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.repay_amount
     *
     * @param repayAmount the value for jk.t_jk_payback_list.repay_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setRepayAmount(BigDecimal repayAmount) {
        this.repayAmount = repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.complete_amount
     *
     * @return the value of jk.t_jk_payback_list.complete_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public BigDecimal getCompleteAmount() {
        return completeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.complete_amount
     *
     * @param completeAmount the value for jk.t_jk_payback_list.complete_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setCompleteAmount(BigDecimal completeAmount) {
        this.completeAmount = completeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.bule_amount
     *
     * @return the value of jk.t_jk_payback_list.bule_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public BigDecimal getBuleAmount() {
        return buleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.bule_amount
     *
     * @param buleAmount the value for jk.t_jk_payback_list.bule_amount
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setBuleAmount(BigDecimal buleAmount) {
        this.buleAmount = buleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.dict_month_status
     *
     * @return the value of jk.t_jk_payback_list.dict_month_status
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getDictMonthStatus() {
        return dictMonthStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.dict_month_status
     *
     * @param dictMonthStatus the value for jk.t_jk_payback_list.dict_month_status
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setDictMonthStatus(String dictMonthStatus) {
        this.dictMonthStatus = dictMonthStatus == null ? null : dictMonthStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.status
     *
     * @return the value of jk.t_jk_payback_list.status
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.status
     *
     * @param status the value for jk.t_jk_payback_list.status
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.mark
     *
     * @return the value of jk.t_jk_payback_list.mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.mark
     *
     * @param mark the value for jk.t_jk_payback_list.mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.dict_deal_type
     *
     * @return the value of jk.t_jk_payback_list.dict_deal_type
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getDictDealType() {
        return dictDealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.dict_deal_type
     *
     * @param dictDealType the value for jk.t_jk_payback_list.dict_deal_type
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setDictDealType(String dictDealType) {
        this.dictDealType = dictDealType == null ? null : dictDealType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.stores_mark
     *
     * @return the value of jk.t_jk_payback_list.stores_mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getStoresMark() {
        return storesMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.stores_mark
     *
     * @param storesMark the value for jk.t_jk_payback_list.stores_mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setStoresMark(String storesMark) {
        this.storesMark = storesMark == null ? null : storesMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.stores_mark_userid
     *
     * @return the value of jk.t_jk_payback_list.stores_mark_userid
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getStoresMarkUserid() {
        return storesMarkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.stores_mark_userid
     *
     * @param storesMarkUserid the value for jk.t_jk_payback_list.stores_mark_userid
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setStoresMarkUserid(String storesMarkUserid) {
        this.storesMarkUserid = storesMarkUserid == null ? null : storesMarkUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.riskcontrol_mark
     *
     * @return the value of jk.t_jk_payback_list.riskcontrol_mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getRiskcontrolMark() {
        return riskcontrolMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.riskcontrol_mark
     *
     * @param riskcontrolMark the value for jk.t_jk_payback_list.riskcontrol_mark
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setRiskcontrolMark(String riskcontrolMark) {
        this.riskcontrolMark = riskcontrolMark == null ? null : riskcontrolMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.riskcontrol_remark_userid
     *
     * @return the value of jk.t_jk_payback_list.riskcontrol_remark_userid
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getRiskcontrolRemarkUserid() {
        return riskcontrolRemarkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.riskcontrol_remark_userid
     *
     * @param riskcontrolRemarkUserid the value for jk.t_jk_payback_list.riskcontrol_remark_userid
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setRiskcontrolRemarkUserid(String riskcontrolRemarkUserid) {
        this.riskcontrolRemarkUserid = riskcontrolRemarkUserid == null ? null : riskcontrolRemarkUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.create_by
     *
     * @return the value of jk.t_jk_payback_list.create_by
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.create_by
     *
     * @param createBy the value for jk.t_jk_payback_list.create_by
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.create_time
     *
     * @return the value of jk.t_jk_payback_list.create_time
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.create_time
     *
     * @param createTime the value for jk.t_jk_payback_list.create_time
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.modify_by
     *
     * @return the value of jk.t_jk_payback_list.modify_by
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.modify_by
     *
     * @param modifyBy the value for jk.t_jk_payback_list.modify_by
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_jk_payback_list.modify_time
     *
     * @return the value of jk.t_jk_payback_list.modify_time
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_jk_payback_list.modify_time
     *
     * @param modifyTime the value for jk.t_jk_payback_list.modify_time
     *
     * @mbggenerated Tue Dec 22 10:01:51 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

	/**
	 * @return the monthPayTotal
	 */
	public BigDecimal getMonthPayTotal() {
		return monthPayTotal;
	}

	/**
	 * @param monthPayTotal the monthPayTotal to set
	 */
	public void setMonthPayTotal(BigDecimal monthPayTotal) {
		this.monthPayTotal = monthPayTotal;
	}

	/**
	 * @return the returnReasion
	 */
	public String getReturnReasion() {
		return returnReasion;
	}

	/**
	 * @param returnReasion the returnReasion to set
	 */
	public void setReturnReasion(String returnReasion) {
		this.returnReasion = returnReasion;
	}
}