package com.creditharmony.loan.borrow.sms.entity;

import java.util.Date;

public class SmsHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.loan_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String loanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.customer_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.customer_name
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.sms_send_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private Date smsSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String smsMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String smsTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.sms_send_status
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String smsSendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.only_flag
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String onlyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.create_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.create_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.modify_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_his.modify_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.id
     *
     * @return the value of jk.t_gl_sms_jk_his.id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.id
     *
     * @param id the value for jk.t_gl_sms_jk_his.id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.loan_code
     *
     * @return the value of jk.t_gl_sms_jk_his.loan_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getLoanCode() {
        return loanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.loan_code
     *
     * @param loanCode the value for jk.t_gl_sms_jk_his.loan_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setLoanCode(String loanCode) {
        this.loanCode = loanCode == null ? null : loanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.customer_code
     *
     * @return the value of jk.t_gl_sms_jk_his.customer_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.customer_code
     *
     * @param customerCode the value for jk.t_gl_sms_jk_his.customer_code
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.customer_name
     *
     * @return the value of jk.t_gl_sms_jk_his.customer_name
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.customer_name
     *
     * @param customerName the value for jk.t_gl_sms_jk_his.customer_name
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.sms_send_time
     *
     * @return the value of jk.t_gl_sms_jk_his.sms_send_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public Date getSmsSendTime() {
        return smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.sms_send_time
     *
     * @param smsSendTime the value for jk.t_gl_sms_jk_his.sms_send_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setSmsSendTime(Date smsSendTime) {
        this.smsSendTime = smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.sms_msg
     *
     * @return the value of jk.t_gl_sms_jk_his.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getSmsMsg() {
        return smsMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.sms_msg
     *
     * @param smsMsg the value for jk.t_gl_sms_jk_his.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setSmsMsg(String smsMsg) {
        this.smsMsg = smsMsg == null ? null : smsMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.sms_template_id
     *
     * @return the value of jk.t_gl_sms_jk_his.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getSmsTemplateId() {
        return smsTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.sms_template_id
     *
     * @param smsTemplateId the value for jk.t_gl_sms_jk_his.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setSmsTemplateId(String smsTemplateId) {
        this.smsTemplateId = smsTemplateId == null ? null : smsTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.sms_send_status
     *
     * @return the value of jk.t_gl_sms_jk_his.sms_send_status
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getSmsSendStatus() {
        return smsSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.sms_send_status
     *
     * @param smsSendStatus the value for jk.t_gl_sms_jk_his.sms_send_status
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setSmsSendStatus(String smsSendStatus) {
        this.smsSendStatus = smsSendStatus == null ? null : smsSendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.only_flag
     *
     * @return the value of jk.t_gl_sms_jk_his.only_flag
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getOnlyFlag() {
        return onlyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.only_flag
     *
     * @param onlyFlag the value for jk.t_gl_sms_jk_his.only_flag
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setOnlyFlag(String onlyFlag) {
        this.onlyFlag = onlyFlag == null ? null : onlyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.create_by
     *
     * @return the value of jk.t_gl_sms_jk_his.create_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.create_by
     *
     * @param createBy the value for jk.t_gl_sms_jk_his.create_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.create_time
     *
     * @return the value of jk.t_gl_sms_jk_his.create_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.create_time
     *
     * @param createTime the value for jk.t_gl_sms_jk_his.create_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.modify_by
     *
     * @return the value of jk.t_gl_sms_jk_his.modify_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.modify_by
     *
     * @param modifyBy the value for jk.t_gl_sms_jk_his.modify_by
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_his.modify_time
     *
     * @return the value of jk.t_gl_sms_jk_his.modify_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_his.modify_time
     *
     * @param modifyTime the value for jk.t_gl_sms_jk_his.modify_time
     *
     * @mbggenerated Tue Dec 22 11:46:48 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}