package com.creditharmony.loan.borrow.sms.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SmsSendList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.loan_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String loanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.customer_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.customer_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.product_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.phone
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private Date repayDay;

    private String selectRepayDay;
    
    public String getSelectRepayDay() {
		return selectRepayDay;
	}

	public void setSelectRepayDay(String selectRepayDay) {
		this.selectRepayDay = selectRepayDay;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.first_repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private Date firstRepayDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.repay_amount
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private BigDecimal repayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.dict_loan_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String dictLoanStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.bank_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.bank_card_no
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String bankCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String smsTemplateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String smsMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.send_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String sendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.send_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.effective_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String effectiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.stores_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String storesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.only_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String onlyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.create_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.create_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.modify_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jk.t_gl_sms_jk_send_list.modify_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private Date modifyTime;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.id
     *
     * @return the value of jk.t_gl_sms_jk_send_list.id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    private String SmsModelName;
    
    
    public String getSmsModelName() {
		return SmsModelName;
	}

	public void setSmsModelName(String smsModelName) {
		SmsModelName = smsModelName;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.id
     *
     * @param id the value for jk.t_gl_sms_jk_send_list.id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.loan_code
     *
     * @return the value of jk.t_gl_sms_jk_send_list.loan_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getLoanCode() {
        return loanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.loan_code
     *
     * @param loanCode the value for jk.t_gl_sms_jk_send_list.loan_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setLoanCode(String loanCode) {
        this.loanCode = loanCode == null ? null : loanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.customer_code
     *
     * @return the value of jk.t_gl_sms_jk_send_list.customer_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.customer_code
     *
     * @param customerCode the value for jk.t_gl_sms_jk_send_list.customer_code
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.customer_name
     *
     * @return the value of jk.t_gl_sms_jk_send_list.customer_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.customer_name
     *
     * @param customerName the value for jk.t_gl_sms_jk_send_list.customer_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.product_name
     *
     * @return the value of jk.t_gl_sms_jk_send_list.product_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.product_name
     *
     * @param productName the value for jk.t_gl_sms_jk_send_list.product_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.phone
     *
     * @return the value of jk.t_gl_sms_jk_send_list.phone
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.phone
     *
     * @param phone the value for jk.t_gl_sms_jk_send_list.phone
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.repay_day
     *
     * @return the value of jk.t_gl_sms_jk_send_list.repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public Date getRepayDay() {
        return repayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.repay_day
     *
     * @param repayDay the value for jk.t_gl_sms_jk_send_list.repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setRepayDay(Date repayDay) {
        this.repayDay = repayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.first_repay_day
     *
     * @return the value of jk.t_gl_sms_jk_send_list.first_repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public Date getFirstRepayDay() {
        return firstRepayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.first_repay_day
     *
     * @param firstRepayDay the value for jk.t_gl_sms_jk_send_list.first_repay_day
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setFirstRepayDay(Date firstRepayDay) {
        this.firstRepayDay = firstRepayDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.repay_amount
     *
     * @return the value of jk.t_gl_sms_jk_send_list.repay_amount
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public BigDecimal getRepayAmount() {
        return repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.repay_amount
     *
     * @param repayAmount the value for jk.t_gl_sms_jk_send_list.repay_amount
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setRepayAmount(BigDecimal repayAmount) {
        this.repayAmount = repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.dict_loan_status
     *
     * @return the value of jk.t_gl_sms_jk_send_list.dict_loan_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getDictLoanStatus() {
        return dictLoanStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.dict_loan_status
     *
     * @param dictLoanStatus the value for jk.t_gl_sms_jk_send_list.dict_loan_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setDictLoanStatus(String dictLoanStatus) {
        this.dictLoanStatus = dictLoanStatus == null ? null : dictLoanStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.bank_name
     *
     * @return the value of jk.t_gl_sms_jk_send_list.bank_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.bank_name
     *
     * @param bankName the value for jk.t_gl_sms_jk_send_list.bank_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.bank_card_no
     *
     * @return the value of jk.t_gl_sms_jk_send_list.bank_card_no
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getBankCardNo() {
        return bankCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.bank_card_no
     *
     * @param bankCardNo the value for jk.t_gl_sms_jk_send_list.bank_card_no
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo == null ? null : bankCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.sms_template_id
     *
     * @return the value of jk.t_gl_sms_jk_send_list.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getSmsTemplateId() {
        return smsTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.sms_template_id
     *
     * @param smsTemplateId the value for jk.t_gl_sms_jk_send_list.sms_template_id
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setSmsTemplateId(String smsTemplateId) {
        this.smsTemplateId = smsTemplateId == null ? null : smsTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.sms_msg
     *
     * @return the value of jk.t_gl_sms_jk_send_list.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getSmsMsg() {
        return smsMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.sms_msg
     *
     * @param smsMsg the value for jk.t_gl_sms_jk_send_list.sms_msg
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setSmsMsg(String smsMsg) {
        this.smsMsg = smsMsg == null ? null : smsMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.send_status
     *
     * @return the value of jk.t_gl_sms_jk_send_list.send_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.send_status
     *
     * @param sendStatus the value for jk.t_gl_sms_jk_send_list.send_status
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.send_time
     *
     * @return the value of jk.t_gl_sms_jk_send_list.send_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.send_time
     *
     * @param sendTime the value for jk.t_gl_sms_jk_send_list.send_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.effective_flag
     *
     * @return the value of jk.t_gl_sms_jk_send_list.effective_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getEffectiveFlag() {
        return effectiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.effective_flag
     *
     * @param effectiveFlag the value for jk.t_gl_sms_jk_send_list.effective_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setEffectiveFlag(String effectiveFlag) {
        this.effectiveFlag = effectiveFlag == null ? null : effectiveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.stores_name
     *
     * @return the value of jk.t_gl_sms_jk_send_list.stores_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getStoresName() {
        return storesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.stores_name
     *
     * @param storesName the value for jk.t_gl_sms_jk_send_list.stores_name
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setStoresName(String storesName) {
        this.storesName = storesName == null ? null : storesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.only_flag
     *
     * @return the value of jk.t_gl_sms_jk_send_list.only_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getOnlyFlag() {
        return onlyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.only_flag
     *
     * @param onlyFlag the value for jk.t_gl_sms_jk_send_list.only_flag
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setOnlyFlag(String onlyFlag) {
        this.onlyFlag = onlyFlag == null ? null : onlyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.create_by
     *
     * @return the value of jk.t_gl_sms_jk_send_list.create_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.create_by
     *
     * @param createBy the value for jk.t_gl_sms_jk_send_list.create_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.create_time
     *
     * @return the value of jk.t_gl_sms_jk_send_list.create_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.create_time
     *
     * @param createTime the value for jk.t_gl_sms_jk_send_list.create_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.modify_by
     *
     * @return the value of jk.t_gl_sms_jk_send_list.modify_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.modify_by
     *
     * @param modifyBy the value for jk.t_gl_sms_jk_send_list.modify_by
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy == null ? null : modifyBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jk.t_gl_sms_jk_send_list.modify_time
     *
     * @return the value of jk.t_gl_sms_jk_send_list.modify_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jk.t_gl_sms_jk_send_list.modify_time
     *
     * @param modifyTime the value for jk.t_gl_sms_jk_send_list.modify_time
     *
     * @mbggenerated Tue Dec 22 11:43:41 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}